"""Начальная схема: пользователи, турниры, туры, матчи, прогнозы, архивные таблицы.

Revision ID: 0001
Revises:
Create Date: 2026-09-25 04:47:09.338132
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import bot.database.models

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', name='tournament_status', native_enum=False, create_constraint=True), server_default='active', nullable=False),
    sa.Column('created_at', bot.database.models.UtcDateTime(), nullable=False),
    sa.Column('archived_at', bot.database.models.UtcDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tournaments'))
    )
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.create_index('ux_tournaments_one_active', ['status'], unique=True, sqlite_where=sa.text("status = 'active'"), postgresql_where=sa.text("status = 'active'"))

    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('nickname', sa.String(length=32), nullable=False),
    sa.Column('nickname_key', sa.String(length=32), nullable=False),
    sa.Column('tg_username', sa.String(length=32), nullable=True),
    sa.Column('is_banned', sa.Boolean(create_constraint=True, name='is_banned'), server_default=sa.false(), nullable=False),
    sa.Column('created_at', bot.database.models.UtcDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id', name=op.f('pk_users')),
    sa.UniqueConstraint('nickname_key', name=op.f('uq_users_nickname_key'))
    )
    op.create_table('leaderboard_snapshots',
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('nickname', sa.String(length=32), nullable=False),
    sa.Column('place', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('predictions_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_leaderboard_snapshots_tournament_id_tournaments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], name=op.f('fk_leaderboard_snapshots_user_id_users')),
    sa.PrimaryKeyConstraint('tournament_id', 'user_id', name=op.f('pk_leaderboard_snapshots'))
    )
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('deadline_at', bot.database.models.UtcDateTime(), nullable=False),
    sa.Column('created_at', bot.database.models.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_rounds_tournament_id_tournaments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rounds'))
    )
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rounds_tournament_id'), ['tournament_id'], unique=False)

    op.create_table('matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('home_team', sa.String(length=64), nullable=False),
    sa.Column('away_team', sa.String(length=64), nullable=False),
    sa.Column('starts_at', bot.database.models.UtcDateTime(), nullable=False),
    sa.Column('result', sa.Enum('1', 'X', '2', name='result', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'finished', 'cancelled', name='match_status', native_enum=False, create_constraint=True), server_default='scheduled', nullable=False),
    sa.Column('created_at', bot.database.models.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], name=op.f('fk_matches_round_id_rounds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matches'))
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matches_round_id'), ['round_id'], unique=False)

    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.Enum('1', 'X', '2', name='outcome', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', bot.database.models.UtcDateTime(), nullable=False),
    sa.Column('updated_at', bot.database.models.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_predictions_match_id_matches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], name=op.f('fk_predictions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_predictions')),
    sa.UniqueConstraint('user_id', 'match_id', name=op.f('uq_predictions_user_id_match_id'))
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predictions_match_id'), ['match_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predictions_match_id'))

    op.drop_table('predictions')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_round_id'))

    op.drop_table('matches')
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rounds_tournament_id'))

    op.drop_table('rounds')
    op.drop_table('leaderboard_snapshots')
    op.drop_table('users')
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_index('ux_tournaments_one_active', sqlite_where=sa.text("status = 'active'"), postgresql_where=sa.text("status = 'active'"))

    op.drop_table('tournaments')
    # ### end Alembic commands ###
