"""Администраторы, назначенные через бот (любым админом).

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-25 17:56:22.638114
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import bot.database.models

revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('added_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', bot.database.models.UtcDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admins')),
    sa.UniqueConstraint('telegram_id', name=op.f('uq_admins_telegram_id')),
    sa.UniqueConstraint('username', name=op.f('uq_admins_username'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admins')
    # ### end Alembic commands ###
